version: "3.8"

services:
  db:
    image: mysql:8.0.22
    container_name: appsDB
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /home/nickson/db-data:/var/lib/mysql

    networks:
        - data
    
  app:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
    networks: 
      - data

  jenkins:
    build:
      context: ./jenkins
    deploy:
      labels:
        jenkins.description: "Creating jenkins and adding users"
    ports:
      - "8081:8080"
    volumes:
      - /home/nickson/jenkins_home:/var/jenkins_home
    networks:
     - jenkins
volumes:
  db-data:

networks:
  jenkins:
  data: